# Загальна інформація
site_name: Документація до калькулятора
site_author: Вікторія Бродовська
site_description: 'Проста та зрозуміла документація для консольного калькулятора'

# Налаштування зовнішнього вигляду
theme: 
name: material
language: uk # Додамо українську мову для елементів інтерфейсу

# Налаштування структури навігаційого меню
 - 'Головна': 'index.md'
 - 'Посібник користувача':
   - 'Встановлення': 'guide/installation.md'
   - 'Приклади використання': 'guide/usage.md'
 - 'Про проєкт': 'about.md'